### PR TITLE
Slider improvements wants to be merged into master

### PR DESCRIPTION
**Pull request by IsabelKoe**
Hi, I am done with the slider/banner component. I've already merged the master into the branch and solved the conflicts. Please review my code so we can merge this branch into the master. Thanks, Isabel

### CODE REVIEW

**Review by on21KatB — CHANGES_REQUESTED** [review]
There is a component "jplants-sliderOld"- I think this can be deleted? And in the folder "jplants-slider" there are two .css and two .tsx files, probably the files named "jplants-slide" are not needed? 
Otherwise it looks good to me!

**Comment by IsabelKoe** [comment]
Hey - with regards to the sliderOld file. Yes I think we can delete it. It was my old version trying to get the slider working. I just did not want to delete it from the improvement branch. With regards to the slide and slider component, we need both as the slide is the single file shown in the slider. The current slider consists of three slides components.

**Review by on21viktoria — APPROVED** [review]
Sieht gut aus

**Comment by IsabelKoe** [comment]
Merges refined master agin into branch and solved all merge conflicts.

**Pull request merged**
